name: testing labels

on:
  push:
    branches: feature/fix_snyk

jobs:
  labels:
    permissions:
      contents: write
#       pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: New Release Publish
        uses: release-drafter/release-drafter@v5
        with:
          publish : true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
    
